//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattClient_MVC.QuoteServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuoteServiceRef.IQuoteService")]
    public interface IQuoteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteService/Get", ReplyAction="http://tempuri.org/IQuoteService/GetResponse")]
        string Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteService/Get", ReplyAction="http://tempuri.org/IQuoteService/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuoteServiceChannel : ChattClient_MVC.QuoteServiceRef.IQuoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuoteServiceClient : System.ServiceModel.ClientBase<ChattClient_MVC.QuoteServiceRef.IQuoteService>, ChattClient_MVC.QuoteServiceRef.IQuoteService {
        
        public QuoteServiceClient() {
        }
        
        public QuoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<string> GetAsync() {
            return base.Channel.GetAsync();
        }
    }
}
